-- RUN AS SYSTEM USER AGAINST SYSTEM DATABASE

-- CHECK AFL PAL FUNCTIONS ARE INSTALLED
SELECT * FROM SYS.AFL_FUNCTIONS WHERE PACKAGE_NAME='PAL';

-- CREATE TENANT DATABASE
CREATE DATABASE SHA SYSTEM USER PASSWORD Password1;

-- ACTIVATE SCRIPTSERVER ON TENANT DATABASE
ALTER DATABASE SHA ADD 'scriptserver';

----------------------------------------------------------------------------------------

-- RUN AS SYSTEM USER AGAINST TENANT DATABASE

-- CREATE USER FOR DEVELOPMENT
CREATE USER DEVUSER PASSWORD Password1;

-- AUTHORIZE CREATION & REMOVAL OF PAL PROCEDURES
GRANT AFLPM_CREATOR_ERASER_EXECUTE TO DEVUSER;

-- AUTHORIZE EXECUTION OF PAL PROCEDURES
GRANT AFL__SYS_AFL_AFLPAL_EXECUTE TO DEVUSER;

-- ENABLE MODELING
GRANT MODELING TO DEVUSER;

-- ENABLE HANA NATIVE DEVELOPMENT
GRANT EXECUTE ON REPOSITORY_REST TO DEVUSER;
GRANT REPO.READ, REPO.EDIT_NATIVE_OBJECTS, REPO.ACTIVATE_NATIVE_OBJECTS, REPO.MAINTAIN_NATIVE_PACKAGES ON ".REPO_PACKAGE_ROOT" TO DEVUSER;

-- IMPORT SAMPLE SCHEMA VIA ECLIPSE FILE>IMPORT WIZARD

-- AUTHORIZE READ ACCESS TO SAMPLE SCHEMA
GRANT SELECT ON SCHEMA PAL TO DEVUSER;

-- GRANT REPOSITORY TECH USER ACCESS TO SAMPLE SCHEMA
GRANT SELECT ON SCHEMA PAL TO _SYS_REPO;

----------------------------------------------------------------------------------------

-- RUN AS DEVUSER AGAINST TENANT DATABASE

-- GRANT REPOSITORY TECH USER ACCESS TO DEVUSER SCHEMA
GRANT SELECT, INSERT, DELETE ON SCHEMA DEVUSER TO _SYS_REPO;
